### ISSUE TITLE
Note

### ISSUE THREAD

**Issue by DevX-Cipher** [stopcallingmyname/Metadata-dumper#1]
This only works if it is written in C# not C++

**Comment by stopcallingmyname** [comment]
Can you describe the problem in more detail, and also indicate which game you are testing the dumper on?

**Comment by DevX-Cipher** [comment]
well if a unity gave is compiled into C++ you cant read the meta data from it

**Comment by stopcallingmyname** [comment]
> well if a unity gave is compiled into C++ you cant read the meta data from it

If you mean the Il2cpp compilation of Unity games, this dumper was written to dump metadata if it has been encrypted by the developer and cannot be read by Il2CppDumper. If the metadata is not encrypted and the build method is Il2cpp, then there is no need to use this dumper, as the file can be easily read. It's important to understand that Metadata-dumper is used specifically for dumping encrypted metadata of games built with Il2cpp.

**Comment by DevX-Cipher** [comment]
yes it is but i have moved on from this now
